stages:
  - build

build_job:
  stage: build
  image: node:18-alpine
  script:
    - npm install
    - npm run build
  tags:
    - hva
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      when: always